### ISSUE TITLE
Delete unused products command not working

### ISSUE THREAD

**Issue by supp429** [compozed/ops_manager_cli#1]
# GOFUS

```
ops_manager delete-unused-products
/Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ops_manager_cli-0.2.0/lib/ops_manager/cli.rb:70:in `execute': undefined method `delete_products' for #<OpsManager:0x007fb3a63c8708> (NoMethodError)
        from /Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
        from /Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
        from /Users/localadmin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ops_manager_cli-0.2.0/exe/ops_manager:4:in `<top (required)>'
        from /Users/localadmin/.rbenv/versions/2.2.3/bin/ops_manager:23:in `load'
        from /Users/localadmin/.rbenv/versions/2.2.3/bin/ops_manager:23:in `<main>'
```

**Comment by bonzofenix** [comment]
This issue is fixed in the current version
